name: build

on: [push]

jobs:
  build-and-push-image:
      runs-on: ubuntu-latest
      env:
        REGISTRY: ghcr.io
        IMAGE_NAME: metaflow-ui-backend

      permissions:
        contents: read
        packages: write

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Log in to the Container registry
          uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to GitHub Container Registry
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build and push
          run: |
            docker-compose -f docker-compose.development.yml build ui_backend
            docker tag rezashabrang/${{ env.IMAGE_NAME }} ghcr.io/rezashabrang/${{ env.IMAGE_NAME }}:latest
            docker push ghcr.io/rezashabrang/${{ env.IMAGE_NAME }}:latest