name: build

on: [push]

jobs:
  build-and-push-image:
      runs-on: ubuntu-latest
      env:
        REGISTRY: ghcr.io
        IMAGE_NAME: metaflow-ui-backend

      permissions:
        contents: read
        packages: write

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Log in to the Container registry
          uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to GitHub Container Registry
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: build & push metadata service
          run: |
            docker-compose -f docker-compose.development.yml build metadata
            docker tag rezashabrang/metaflow-metadata ghcr.io/rezashabrang/metaflow-metadata:latest
            docker push ghcr.io/rezashabrang/metaflow-metadata:latest

        - name: build & push migration service
          run: |
            docker-compose -f docker-compose.development.yml build migration
            docker tag rezashabrang/metaflow-migration ghcr.io/rezashabrang/metaflow-migration:latest
            docker push ghcr.io/rezashabrang/metaflow-migration:latest

        - name: build & push ui-backend
          run: |
            docker-compose -f docker-compose.development.yml build ui_backend
            docker tag rezashabrang/metaflow-ui-backend ghcr.io/rezashabrang/metaflow-ui-backend:latest
            docker push ghcr.io/rezashabrang/metaflow-ui-backend:latest